/*
Authors:
Axel Isaksson,
F Lundevall,
Elias Hollstrand,
Mattias Kvist

Date: 2023-11-01

For copyright and licensing, see file COPYING
*/

#include <stdint.h>	 /* Declarations of uint_32 and the like */
#include <pic32mx.h> /* Declarations of system-specific addresses etc */
#include "declare.h" /* Declatations for these labs */

static int FPS = 10;

int character_x = 10;
int character_y = 10;
int i = 0;

void user_isr(void)
{
	if (IFS(0) & 0x100)
	{

		// Clear the interrupt flag
		IFSCLR(0) = 0x100;
		update_display();

		// Update the display
		// update_display();
	}

}

void update_display(void)
{
	// Clear the display
	clear_all_pixels();

	move_character();

	// Update the display
	display_objects();

	// Update the display
	// display_update();
}

void move_character()
{
	character_x++;
	fill_rectangle(character_x, character_y, 10, 10);
}

int main(void)
{
// 	/*
//   This will set the peripheral bus clock to the same frequency
//   as the sysclock. That means 80 MHz, when the microcontroller
//   is running at 80 MHz. Changed 2017, as recommended by Axel.
// */
// 	SYSKEY = 0xAA996655; /* Unlock OSCCON, step 1 */
// 	SYSKEY = 0x556699AA; /* Unlock OSCCON, step 2 */
// 	while (OSCCON & (1 << 21))
// 		;				  /* Wait until PBDIV ready */
// 	OSCCONCLR = 0x180000; /* clear PBDIV bit <0,1> */
// 	while (OSCCON & (1 << 21))
// 		;		  /* Wait until PBDIV ready */
// 	SYSKEY = 0x0; /* Lock OSCCON */

// 	/* Set up output pins */
// 	AD1PCFG = 0xFFFF;
// 	ODCE = 0x0;
// 	TRISECLR = 0xFF;
// 	PORTE = 0x0;

// 	/* Output pins for display signals */
// 	PORTF = 0xFFFF;
// 	PORTG = (1 << 9);
// 	ODCF = 0x0;
// 	ODCG = 0x0;
// 	TRISFCLR = 0x70;
// 	TRISGCLR = 0x200;

// 	/* Set up input pins */
// 	TRISDSET = (1 << 8);
// 	TRISFSET = (1 << 1);

// 	/* Set up SPI as master */
// 	SPI2CON = 0;
// 	SPI2BRG = 4;
// 	/* SPI2STAT bit SPIROV = 0; */
// 	SPI2STATCLR = 0x40;
// 	/* SPI2CON bit CKP = 1; */
// 	SPI2CONSET = 0x40;
// 	/* SPI2CON bit MSTEN = 1; */
// 	SPI2CONSET = 0x20;
// 	/* SPI2CON bit ON = 1; */
// 	SPI2CONSET = 0x8000;

// 	TRISD = TRISD | 0x80;
// 	// CNCON = 0x8000;

// 	// IECSET(0) = 0x80000;
// 	// IECSET(0) = 0x80000;
// 	// IECSET(1) = 0x1;
// 	// IPCSET(4) = 0x1c000000;
// 	// IPCSET(6) = 0x1C0000;
// 	// CNEN = 0x10000;

// 	TRISDSET = (1 << 8);
// 	TRISFSET = (1 << 1);

// 	// IECSET(0) = 0x80000;	// Enable switch 4 interrupts (bit 19)
// 	// IECSET(0) = 0x8000;		// Enable switch 3 interrupts (bit 15)
// 	// IECSET(0) = 0x800;		// Enable switch 2 interrupts (bit 11)
// 	// IECSET(0) = 0x80;		// Enable switch 1 interrupts (bit 7)
// 	// IPCSET(2) = 0b11100;	// Set priority level 7
// 	// IPCSET(4) = 0x1c000000; // Set priority level 7 // Bits 28-26
// 							// Initialize port D so that bits 11 through 5 of Port D are set as inputs
// 	TRISD = TRISD | 0x0fe0;

// 	// Set up i2c
// 	I2C1CON = 0x0;
// 	/* I2C Baud rate should be less than 400 kHz, is generated by dividing
// 	the 40 MHz peripheral bus clock down */
// 	I2C1BRG = 0x0C2;
// 	I2C1STAT = 0x0;
// 	// I2C1CONSET = 1 << 13; // SIDL = 1 (disables I2C when CPU is idle)
// 	I2C1CON = 1 << 15;	 // I2C ON
// 	I2C1ADD = 0b1010000; // add EEPROM address to I2C1ADD register

// 	// Configure Timer 2 (T2) for 100 ms timeouts
// 	T2CON = 0x8070; // Enable T2 with prescaler 1:256 (bit 6 and 7)
// 	TMR2 = 0x0;	// Clear the timer counter
// 	PR2 = (80000000 / 256) / 10;  // Set period to 100ms// Set the period register for 100 ms (assuming a 80 MHz clock)
// 	IECSET(0) = 0x100;		// Enable T2 interrupts (bit 8)
// 	IPCSET(2) = 0x1F;             // Set priority 7 and subpriority 3

// 	// Enable global interrupts
// 	enable_interrupt();

	/* Set up peripheral bus clock */
  /* OSCCONbits.PBDIV = 1; */
  OSCCONCLR = 0x100000; /* clear PBDIV bit 1 */
	OSCCONSET = 0x080000; /* set PBDIV bit 0 */

	/* Set up output pins */
	AD1PCFG = 0xFFFF;
	ODCE = 0x0;
	TRISECLR = 0xFF;
	PORTE = 0x0;

	/* Output pins for display signals */
	PORTF = 0xFFFF;
	PORTG = (1 << 9);
	ODCF = 0x0;
	ODCG = 0x0;
	TRISFCLR = 0x70;
	TRISGCLR = 0x200;
  TRISECLR = 0xFF;

	/* Set up input pins */
	TRISFSET = 0x2; // Button 1
	TRISDSET = 0xE0; // Buttons 2-4
  TRISDSET = 0xF00; // Switches 1-4

  /* Set up output pins */
  TRISECLR = 0xFF;

	/* Set up SPI as master */
	SPI2CON = 0;
	SPI2BRG = 4;
	/* SPI2STAT bit SPIROV = 0; */
	SPI2STATCLR = 0x40;
	/* SPI2CON bit CKP = 1; */
  SPI2CONSET = 0x40;
	/* SPI2CON bit MSTEN = 1; */
	SPI2CONSET = 0x20;
	/* SPI2CON bit ON = 1; */
	SPI2CONSET = 0x8000;

	display_init();

  /* Set up clock */
  /* Initialize clock */
  T2CON = 0x70;              // Stop timer and set prescaling to 1:256

  TMR2 = 0;                     // Reset counter
  PR2 = (80000000 / 256) / 10;  // Set period to 100ms

  IPCSET(2) = 0x1F;             // Set priority 7 and subpriority 3
  IFSCLR(0) = (1 << 8);         // Clear interrupt flag for timer 2
  IECSET(0) = (1 << 8);         // Enable interrupts for timer 2

  /* Initialize I2C */
  I2C1CON = 0x0;            // Clear control register
	I2C1BRG = 0x0C2;          // Set Baud Generator Divisor
	I2C1STAT = 0x0;           // Clear status register
	I2C1CONSET = 1 << 13;     // SIDL = 1
  // IPCSET(6) = 0x1B00;       // Set priority 6 and subpriority 3
  // IFSCLR(0) = 0xE0000000;   // Clear interrupt flags for I2C1MIF, I2C1SIF and I2CBIF
  // IECSET(0) = 0xE0000000;   // Enable interrupts for I2C1MIF, I2C1SIF and I2CBIF

  enable_interrupt(); // Enable interrupts globally

  T2CONSET = 0x8000;    // Start clock
  I2C1CONSET = 0x8000;  // Start I2C bus

	// display_init();
	// display_string(0, "Score: ");
	// display_string(2, "Highscore: ");
	// set some pixels to test
	set_pixel(0, 0);
	set_pixel(0, 1);
	set_pixel(13, 13);
	set_pixel(32, 31);
	set_pixel(33, 31);
	set_pixel(34, 31);
	fill_rectangle(10, 10, 10, 10);

	display_objects();

	// score_init();

	// display_image(96, icon);

	while (1)
	{
	}
	return 0;
}
